//-----------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//-----------------------------------------------------------------------------
// This file was auto-generated by Register Manager
//-----------------------------------------------------------------------------

module camera_ctrl_reg_interface
(
  // Ports to functional block
  output [1:0]  frmt_cam_out,
  output [1:0]  res_cam_out,
  output        intr_line_trn_tx_cmt_out,
  input         intr_line_trn_tx_cmt_in,
  input         intr_line_trn_tx_cmt_hw_wr_en_in,
  output        intr_line_input_in_cmt_out,
  input         intr_line_input_in_cmt_in,
  input         intr_line_input_in_cmt_hw_wr_en_in,
  output        intr_frm_trn_tx_cmt_out,
  input         intr_frm_trn_tx_cmt_in,
  input         intr_frm_trn_tx_cmt_hw_wr_en_in,
  output        intr_buffer_over_buf_ovr_out,
  input         intr_buffer_over_buf_ovr_in,
  input         intr_buffer_over_buf_ovr_hw_wr_en_in,
  output        intr_buffer_under_buf_und_out,
  input         intr_buffer_under_buf_und_in,
  input         intr_buffer_under_buf_und_hw_wr_en_in,
  output        intr_mask_buf_under_out,
  output        intr_mask_buf_over_out,
  output        intr_mask_frm_tx_cmt_out,
  output        intr_mask_line_in_cmt_out,
  output        intr_mask_line_tx_cmt_out,
  output        cam_ctrl_en_out,
  output        dma_ctrl_trig_mask_out,
  output        debug_ctrl_sram_buffer_out,
  output        debug_ctrl_debug_en_out,

  // System bus ports
  output        PREADY,
  output [31:0] PRDATA,
  output        PSLVERR,
  input  [6:0]  PADDR,
  input  [2:0]  PPROT,
  input         PSEL,
  input         PENABLE,
  input         PWRITE,
  input  [31:0] PWDATA,
  input  [3:0]  PSTRB,
  input         PCLK,
  input         PRESETn
);

  // Internal bus wires
  wire [31:0] rdata_int;
  wire        err_int;
  wire        ack_int;
  wire [6:0]  address_int;
  wire [31:0] wdata_int;
  wire        rd_int;
  wire        val_int;
  wire [3:0]  be_int;
  wire        secure_int;
  wire        clk_int;
  wire        resetn_int;

  // Bus interface instantiation

  camera_ctrl_bus_interface u_camera_ctrl_bus_interface(
  // System bus ports
    .PREADY(PREADY),
    .PRDATA(PRDATA),
    .PSLVERR(PSLVERR),
    .PADDR(PADDR),
    .PPROT(PPROT),
    .PSEL(PSEL),
    .PENABLE(PENABLE),
    .PWRITE(PWRITE),
    .PWDATA(PWDATA),
    .PSTRB(PSTRB),
    .PCLK(PCLK),
    .PRESETn(PRESETn),

  // Internal ports
    .RDATA_IN(rdata_int),
    .ERR_IN(err_int),
    .ACK_IN(ack_int),
    .ADDRESS_OUT(address_int),
    .WDATA_OUT(wdata_int),
    .RD_OUT(rd_int),
    .VAL_OUT(val_int),
    .BE_OUT(be_int),
    .SECURE_OUT(secure_int),
    .CLK_OUT(clk_int),
    .RESETn_OUT(resetn_int)
  );

  // Register Block instantiation

  camera_ctrl_reg_block u_camera_ctrl_reg_block(
  // Register ports
    .frmt_cam_out(frmt_cam_out),
    .res_cam_out(res_cam_out),
    .intr_line_trn_tx_cmt_out(intr_line_trn_tx_cmt_out),
    .intr_line_trn_tx_cmt_in(intr_line_trn_tx_cmt_in),
    .intr_line_trn_tx_cmt_hw_wr_en_in(intr_line_trn_tx_cmt_hw_wr_en_in),
    .intr_line_input_in_cmt_out(intr_line_input_in_cmt_out),
    .intr_line_input_in_cmt_in(intr_line_input_in_cmt_in),
    .intr_line_input_in_cmt_hw_wr_en_in(intr_line_input_in_cmt_hw_wr_en_in),
    .intr_frm_trn_tx_cmt_out(intr_frm_trn_tx_cmt_out),
    .intr_frm_trn_tx_cmt_in(intr_frm_trn_tx_cmt_in),
    .intr_frm_trn_tx_cmt_hw_wr_en_in(intr_frm_trn_tx_cmt_hw_wr_en_in),
    .intr_buffer_over_buf_ovr_out(intr_buffer_over_buf_ovr_out),
    .intr_buffer_over_buf_ovr_in(intr_buffer_over_buf_ovr_in),
    .intr_buffer_over_buf_ovr_hw_wr_en_in(intr_buffer_over_buf_ovr_hw_wr_en_in),
    .intr_buffer_under_buf_und_out(intr_buffer_under_buf_und_out),
    .intr_buffer_under_buf_und_in(intr_buffer_under_buf_und_in),
    .intr_buffer_under_buf_und_hw_wr_en_in(intr_buffer_under_buf_und_hw_wr_en_in),
    .intr_mask_buf_under_out(intr_mask_buf_under_out),
    .intr_mask_buf_over_out(intr_mask_buf_over_out),
    .intr_mask_frm_tx_cmt_out(intr_mask_frm_tx_cmt_out),
    .intr_mask_line_in_cmt_out(intr_mask_line_in_cmt_out),
    .intr_mask_line_tx_cmt_out(intr_mask_line_tx_cmt_out),
    .cam_ctrl_en_out(cam_ctrl_en_out),
    .dma_ctrl_trig_mask_out(dma_ctrl_trig_mask_out),
    .debug_ctrl_sram_buffer_out(debug_ctrl_sram_buffer_out),
    .debug_ctrl_debug_en_out(debug_ctrl_debug_en_out),

  // Internal bus ports
    .RDATA(rdata_int),
    .ERR(err_int),
    .ACK(ack_int),
    .ADDRESS(address_int),
    .WDATA(wdata_int),
    .RD(rd_int),
    .VAL(val_int),
    .BE(be_int),
    .SECURE(secure_int),
    .CLK(clk_int),
    .RESETn(resetn_int)
  );

endmodule
