//-----------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//-----------------------------------------------------------------------------
// This file was auto-generated by Register Manager
//-----------------------------------------------------------------------------

// Register: frmt
// Offset: 0x0
localparam FRMT_REG_OFFSET_PARAM = 7'b0000000;
localparam FRMT_CAM_BIT_RESET_PARAM = 2'b00;

// Register: res
// Offset: 0x4
localparam RES_REG_OFFSET_PARAM = 7'b0000100;
localparam RES_CAM_BIT_RESET_PARAM = 2'b11;

// Register: intr_line_trn
// Offset: 0x8
localparam INTR_LINE_TRN_REG_OFFSET_PARAM = 7'b0001000;
localparam INTR_LINE_TRN_TX_CMT_BIT_RESET_PARAM = 1'b0;

// Register: intr_line_input
// Offset: 0xc
localparam INTR_LINE_INPUT_REG_OFFSET_PARAM = 7'b0001100;
localparam INTR_LINE_INPUT_IN_CMT_BIT_RESET_PARAM = 1'b0;

// Register: intr_frm_trn
// Offset: 0x10
localparam INTR_FRM_TRN_REG_OFFSET_PARAM = 7'b0010000;
localparam INTR_FRM_TRN_TX_CMT_BIT_RESET_PARAM = 1'b0;

// Register: intr_buffer_over
// Offset: 0x14
localparam INTR_BUFFER_OVER_REG_OFFSET_PARAM = 7'b0010100;
localparam INTR_BUFFER_OVER_BUF_OVR_BIT_RESET_PARAM = 1'b0;

// Register: intr_buffer_under
// Offset: 0x18
localparam INTR_BUFFER_UNDER_REG_OFFSET_PARAM = 7'b0011000;
localparam INTR_BUFFER_UNDER_BUF_UND_BIT_RESET_PARAM = 1'b0;

// Register: intr_mask
// Offset: 0x1c
localparam INTR_MASK_REG_OFFSET_PARAM = 7'b0011100;
localparam INTR_MASK_BUF_UNDER_BIT_RESET_PARAM = 1'b0;
localparam INTR_MASK_BUF_OVER_BIT_RESET_PARAM = 1'b0;
localparam INTR_MASK_FRM_TX_CMT_BIT_RESET_PARAM = 1'b0;
localparam INTR_MASK_LINE_IN_CMT_BIT_RESET_PARAM = 1'b0;
localparam INTR_MASK_LINE_TX_CMT_BIT_RESET_PARAM = 1'b0;

// Register: cam_ctrl
// Offset: 0x20
localparam CAM_CTRL_REG_OFFSET_PARAM = 7'b0100000;
localparam CAM_CTRL_EN_BIT_RESET_PARAM = 1'b0;

// Register: dma_ctrl
// Offset: 0x24
localparam DMA_CTRL_REG_OFFSET_PARAM = 7'b0100100;
localparam DMA_CTRL_TRIG_MASK_BIT_RESET_PARAM = 1'b0;

// Register: debug_ctrl
// Offset: 0x28
localparam DEBUG_CTRL_REG_OFFSET_PARAM = 7'b0101000;
localparam DEBUG_CTRL_SRAM_BUFFER_BIT_RESET_PARAM = 1'b0;
localparam DEBUG_CTRL_DEBUG_EN_BIT_RESET_PARAM = 1'b0;

