//-----------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//-----------------------------------------------------------------------------
// This file was auto-generated by Register Manager
//-----------------------------------------------------------------------------

module camera_ctrl_reg_block
(
  // Ports to functional block
  output [1:0]  frmt_cam_out,
  output [1:0]  res_cam_out,
  output        intr_line_trn_tx_cmt_out,
  input         intr_line_trn_tx_cmt_in,
  input         intr_line_trn_tx_cmt_hw_wr_en_in,
  output        intr_line_input_in_cmt_out,
  input         intr_line_input_in_cmt_in,
  input         intr_line_input_in_cmt_hw_wr_en_in,
  output        intr_frm_trn_tx_cmt_out,
  input         intr_frm_trn_tx_cmt_in,
  input         intr_frm_trn_tx_cmt_hw_wr_en_in,
  output        intr_buffer_over_buf_ovr_out,
  input         intr_buffer_over_buf_ovr_in,
  input         intr_buffer_over_buf_ovr_hw_wr_en_in,
  output        intr_buffer_under_buf_und_out,
  input         intr_buffer_under_buf_und_in,
  input         intr_buffer_under_buf_und_hw_wr_en_in,
  output        intr_mask_buf_under_out,
  output        intr_mask_buf_over_out,
  output        intr_mask_frm_tx_cmt_out,
  output        intr_mask_line_in_cmt_out,
  output        intr_mask_line_tx_cmt_out,
  output        cam_ctrl_en_out,
  output        dma_ctrl_trig_mask_out,
  output        debug_ctrl_sram_buffer_out,
  output        debug_ctrl_debug_en_out,

  // Internal bus ports
  output [31:0] RDATA,
  output        ERR,
  output        ACK,
  input  [31:0] WDATA,
  input  [3:0]  BE,
  input  [6:0]  ADDRESS,
  input         RD,
  input         VAL,
  input         SECURE,
  input         CLK,
  input         RESETn
);

//------------------------------- Registers -----------------------------------

reg  [1:0]  frmt_cam;
wire [1:0]  frmt_cam_next;
reg  [1:0]  res_cam;
wire [1:0]  res_cam_next;
reg         intr_line_trn_tx_cmt;
reg         intr_line_input_in_cmt;
reg         intr_frm_trn_tx_cmt;
reg         intr_buffer_over_buf_ovr;
reg         intr_buffer_under_buf_und;
reg         intr_mask_buf_under;
wire        intr_mask_buf_under_next;
reg         intr_mask_buf_over;
wire        intr_mask_buf_over_next;
reg         intr_mask_frm_tx_cmt;
wire        intr_mask_frm_tx_cmt_next;
reg         intr_mask_line_in_cmt;
wire        intr_mask_line_in_cmt_next;
reg         intr_mask_line_tx_cmt;
wire        intr_mask_line_tx_cmt_next;
reg         cam_ctrl_en;
wire        cam_ctrl_en_next;
reg         dma_ctrl_trig_mask;
wire        dma_ctrl_trig_mask_next;
reg         debug_ctrl_sram_buffer;
wire        debug_ctrl_sram_buffer_next;
reg         debug_ctrl_debug_en;
wire        debug_ctrl_debug_en_next;

//----------------------- Decode enable and read signals ----------------------
wire [31:0] frmt_int;
wire        frmt_rd_en_int;
wire        frmt_wr_en_int;
wire [31:0] res_int;
wire        res_rd_en_int;
wire        res_wr_en_int;
wire [31:0] intr_line_trn_int;
wire        intr_line_trn_rd_en_int;
wire [31:0] intr_line_input_int;
wire        intr_line_input_rd_en_int;
wire [31:0] intr_frm_trn_int;
wire        intr_frm_trn_rd_en_int;
wire [31:0] intr_buffer_over_int;
wire        intr_buffer_over_rd_en_int;
wire [31:0] intr_buffer_under_int;
wire        intr_buffer_under_rd_en_int;
wire [31:0] intr_mask_int;
wire        intr_mask_rd_en_int;
wire        intr_mask_wr_en_int;
wire [31:0] cam_ctrl_int;
wire        cam_ctrl_rd_en_int;
wire        cam_ctrl_wr_en_int;
wire [31:0] dma_ctrl_int;
wire        dma_ctrl_rd_en_int;
wire        dma_ctrl_wr_en_int;
wire [31:0] debug_ctrl_int;
wire        debug_ctrl_rd_en_int;
wire        debug_ctrl_wr_en_int;

//----------------- Internal signals to drive bus output ports ----------------
wire [6:0]  address_int;
reg  [31:0] read_data;

//------------------------ Byte Enable mask signal ----------------------------
wire [31:0] be_mask;

//---------------------- Signals for error response ---------------------------
wire register_read_access;
wire register_write_access;
wire err_int;

`include "camera_ctrl_localparams.sv"

  // Address decoding
  assign frmt_rd_en_int = VAL & RD &
    (address_int[6:2] == FRMT_REG_OFFSET_PARAM[6:2]);

  assign frmt_wr_en_int = VAL & ~RD &
    (address_int[6:2] == FRMT_REG_OFFSET_PARAM[6:2]);

  assign res_rd_en_int = VAL & RD &
    (address_int[6:2] == RES_REG_OFFSET_PARAM[6:2]);

  assign res_wr_en_int = VAL & ~RD &
    (address_int[6:2] == RES_REG_OFFSET_PARAM[6:2]);

  assign intr_line_trn_rd_en_int = VAL & RD &
    (address_int[6:2] == INTR_LINE_TRN_REG_OFFSET_PARAM[6:2]);

  assign intr_line_input_rd_en_int = VAL & RD &
    (address_int[6:2] == INTR_LINE_INPUT_REG_OFFSET_PARAM[6:2]);

  assign intr_frm_trn_rd_en_int = VAL & RD &
    (address_int[6:2] == INTR_FRM_TRN_REG_OFFSET_PARAM[6:2]);

  assign intr_buffer_over_rd_en_int = VAL & RD &
    (address_int[6:2] == INTR_BUFFER_OVER_REG_OFFSET_PARAM[6:2]);

  assign intr_buffer_under_rd_en_int = VAL & RD &
    (address_int[6:2] == INTR_BUFFER_UNDER_REG_OFFSET_PARAM[6:2]);

  assign intr_mask_rd_en_int = VAL & RD &
    (address_int[6:2] == INTR_MASK_REG_OFFSET_PARAM[6:2]);

  assign intr_mask_wr_en_int = VAL & ~RD &
    (address_int[6:2] == INTR_MASK_REG_OFFSET_PARAM[6:2]);

  assign cam_ctrl_rd_en_int = VAL & RD &
    (address_int[6:2] == CAM_CTRL_REG_OFFSET_PARAM[6:2]);

  assign cam_ctrl_wr_en_int = VAL & ~RD &
    (address_int[6:2] == CAM_CTRL_REG_OFFSET_PARAM[6:2]);

  assign dma_ctrl_rd_en_int = VAL & RD &
    (address_int[6:2] == DMA_CTRL_REG_OFFSET_PARAM[6:2]);

  assign dma_ctrl_wr_en_int = VAL & ~RD &
    (address_int[6:2] == DMA_CTRL_REG_OFFSET_PARAM[6:2]);

  assign debug_ctrl_rd_en_int = VAL & RD &
    (address_int[6:2] == DEBUG_CTRL_REG_OFFSET_PARAM[6:2]);

  assign debug_ctrl_wr_en_int = VAL & ~RD &
    (address_int[6:2] == DEBUG_CTRL_REG_OFFSET_PARAM[6:2]);

  // Byte Enable mask
  assign be_mask = (VAL & ~RD)
                   ? {
                       {8{BE[3]}},
                       {8{BE[2]}},
                       {8{BE[1]}},
                       {8{BE[0]}}
                     }
                   : 32'b0;

  // Register access for error response
  assign register_read_access = |{
                                  frmt_rd_en_int,
                                  res_rd_en_int,
                                  intr_line_trn_rd_en_int,
                                  intr_line_input_rd_en_int,
                                  intr_frm_trn_rd_en_int,
                                  intr_buffer_over_rd_en_int,
                                  intr_buffer_under_rd_en_int,
                                  intr_mask_rd_en_int,
                                  cam_ctrl_rd_en_int,
                                  dma_ctrl_rd_en_int,
                                  debug_ctrl_rd_en_int,
                                  1'b0};

  assign register_write_access = |{
                                   frmt_wr_en_int,
                                   res_wr_en_int,
                                   intr_mask_wr_en_int,
                                   cam_ctrl_wr_en_int,
                                   dma_ctrl_wr_en_int,
                                   debug_ctrl_wr_en_int,
                                   1'b0};

  assign err_int = VAL & ((RD & ~register_read_access) | (~RD & ~register_write_access));

  // Internal RW and WO registers and registered RO data

  // frmt_cam
  assign frmt_cam_next[1:0] = (be_mask[1:0] & (WDATA[1:0])) | (~be_mask[1:0] & frmt_cam[1:0]);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      frmt_cam[1:0] <= FRMT_CAM_BIT_RESET_PARAM[1:0];
    end
    else begin
      if (frmt_wr_en_int) begin
        frmt_cam[1:0] <= frmt_cam_next[1:0];
      end
    end
  end // frmt_cam

  // res_cam
  assign res_cam_next[1:0] = (be_mask[1:0] & (WDATA[1:0])) | (~be_mask[1:0] & res_cam[1:0]);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      res_cam[1:0] <= RES_CAM_BIT_RESET_PARAM[1:0];
    end
    else begin
      if (res_wr_en_int) begin
        res_cam[1:0] <= res_cam_next[1:0];
      end
    end
  end // res_cam

  // intr_line_trn_tx_cmt
  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_line_trn_tx_cmt <= INTR_LINE_TRN_TX_CMT_BIT_RESET_PARAM;
    end
    else begin
      if (intr_line_trn_tx_cmt_hw_wr_en_in) begin
        intr_line_trn_tx_cmt <= intr_line_trn_tx_cmt_in;
      end
      else if (intr_line_trn_rd_en_int) begin
        intr_line_trn_tx_cmt <= 1'b0;
      end
    end
  end // intr_line_trn_tx_cmt

  // intr_line_input_in_cmt
  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_line_input_in_cmt <= INTR_LINE_INPUT_IN_CMT_BIT_RESET_PARAM;
    end
    else begin
      if (intr_line_input_in_cmt_hw_wr_en_in) begin
        intr_line_input_in_cmt <= intr_line_input_in_cmt_in;
      end
      else if (intr_line_input_rd_en_int) begin
        intr_line_input_in_cmt <= 1'b0;
      end
    end
  end // intr_line_input_in_cmt

  // intr_frm_trn_tx_cmt
  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_frm_trn_tx_cmt <= INTR_FRM_TRN_TX_CMT_BIT_RESET_PARAM;
    end
    else begin
      if (intr_frm_trn_tx_cmt_hw_wr_en_in) begin
        intr_frm_trn_tx_cmt <= intr_frm_trn_tx_cmt_in;
      end
      else if (intr_frm_trn_rd_en_int) begin
        intr_frm_trn_tx_cmt <= 1'b0;
      end
    end
  end // intr_frm_trn_tx_cmt

  // intr_buffer_over_buf_ovr
  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_buffer_over_buf_ovr <= INTR_BUFFER_OVER_BUF_OVR_BIT_RESET_PARAM;
    end
    else begin
      if (intr_buffer_over_buf_ovr_hw_wr_en_in) begin
        intr_buffer_over_buf_ovr <= intr_buffer_over_buf_ovr_in;
      end
      else if (intr_buffer_over_rd_en_int) begin
        intr_buffer_over_buf_ovr <= 1'b0;
      end
    end
  end // intr_buffer_over_buf_ovr

  // intr_buffer_under_buf_und
  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_buffer_under_buf_und <= INTR_BUFFER_UNDER_BUF_UND_BIT_RESET_PARAM;
    end
    else begin
      if (intr_buffer_under_buf_und_hw_wr_en_in) begin
        intr_buffer_under_buf_und <= intr_buffer_under_buf_und_in;
      end
      else if (intr_buffer_under_rd_en_int) begin
        intr_buffer_under_buf_und <= 1'b0;
      end
    end
  end // intr_buffer_under_buf_und

  // intr_mask_buf_under
  assign intr_mask_buf_under_next = (be_mask[4] & (WDATA[4])) | (~be_mask[4] & intr_mask_buf_under);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_mask_buf_under <= INTR_MASK_BUF_UNDER_BIT_RESET_PARAM;
    end
    else begin
      if (intr_mask_wr_en_int) begin
        intr_mask_buf_under <= intr_mask_buf_under_next;
      end
    end
  end // intr_mask_buf_under

  // intr_mask_buf_over
  assign intr_mask_buf_over_next = (be_mask[3] & (WDATA[3])) | (~be_mask[3] & intr_mask_buf_over);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_mask_buf_over <= INTR_MASK_BUF_OVER_BIT_RESET_PARAM;
    end
    else begin
      if (intr_mask_wr_en_int) begin
        intr_mask_buf_over <= intr_mask_buf_over_next;
      end
    end
  end // intr_mask_buf_over

  // intr_mask_frm_tx_cmt
  assign intr_mask_frm_tx_cmt_next = (be_mask[2] & (WDATA[2])) | (~be_mask[2] & intr_mask_frm_tx_cmt);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_mask_frm_tx_cmt <= INTR_MASK_FRM_TX_CMT_BIT_RESET_PARAM;
    end
    else begin
      if (intr_mask_wr_en_int) begin
        intr_mask_frm_tx_cmt <= intr_mask_frm_tx_cmt_next;
      end
    end
  end // intr_mask_frm_tx_cmt

  // intr_mask_line_in_cmt
  assign intr_mask_line_in_cmt_next = (be_mask[1] & (WDATA[1])) | (~be_mask[1] & intr_mask_line_in_cmt);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_mask_line_in_cmt <= INTR_MASK_LINE_IN_CMT_BIT_RESET_PARAM;
    end
    else begin
      if (intr_mask_wr_en_int) begin
        intr_mask_line_in_cmt <= intr_mask_line_in_cmt_next;
      end
    end
  end // intr_mask_line_in_cmt

  // intr_mask_line_tx_cmt
  assign intr_mask_line_tx_cmt_next = (be_mask[0] & (WDATA[0])) | (~be_mask[0] & intr_mask_line_tx_cmt);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      intr_mask_line_tx_cmt <= INTR_MASK_LINE_TX_CMT_BIT_RESET_PARAM;
    end
    else begin
      if (intr_mask_wr_en_int) begin
        intr_mask_line_tx_cmt <= intr_mask_line_tx_cmt_next;
      end
    end
  end // intr_mask_line_tx_cmt

  // cam_ctrl_en
  assign cam_ctrl_en_next = (be_mask[0] & (WDATA[0])) | (~be_mask[0] & cam_ctrl_en);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      cam_ctrl_en <= CAM_CTRL_EN_BIT_RESET_PARAM;
    end
    else begin
      if (cam_ctrl_wr_en_int) begin
        cam_ctrl_en <= cam_ctrl_en_next;
      end
    end
  end // cam_ctrl_en

  // dma_ctrl_trig_mask
  assign dma_ctrl_trig_mask_next = (be_mask[0] & (WDATA[0])) | (~be_mask[0] & dma_ctrl_trig_mask);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      dma_ctrl_trig_mask <= DMA_CTRL_TRIG_MASK_BIT_RESET_PARAM;
    end
    else begin
      if (dma_ctrl_wr_en_int) begin
        dma_ctrl_trig_mask <= dma_ctrl_trig_mask_next;
      end
    end
  end // dma_ctrl_trig_mask

  // debug_ctrl_sram_buffer
  assign debug_ctrl_sram_buffer_next = (be_mask[1] & (WDATA[1])) | (~be_mask[1] & debug_ctrl_sram_buffer);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      debug_ctrl_sram_buffer <= DEBUG_CTRL_SRAM_BUFFER_BIT_RESET_PARAM;
    end
    else begin
      if (debug_ctrl_wr_en_int) begin
        debug_ctrl_sram_buffer <= debug_ctrl_sram_buffer_next;
      end
    end
  end // debug_ctrl_sram_buffer

  // debug_ctrl_debug_en
  assign debug_ctrl_debug_en_next = (be_mask[0] & (WDATA[0])) | (~be_mask[0] & debug_ctrl_debug_en);

  always @(posedge CLK or negedge RESETn)
  begin
    if (~RESETn) begin
      debug_ctrl_debug_en <= DEBUG_CTRL_DEBUG_EN_BIT_RESET_PARAM;
    end
    else begin
      if (debug_ctrl_wr_en_int) begin
        debug_ctrl_debug_en <= debug_ctrl_debug_en_next;
      end
    end
  end // debug_ctrl_debug_en


  // Make port assigments for HW readable registers

  assign frmt_cam_out = frmt_cam[1:0];
  assign res_cam_out = res_cam[1:0];
  assign intr_line_trn_tx_cmt_out = intr_line_trn_tx_cmt;
  assign intr_line_input_in_cmt_out = intr_line_input_in_cmt;
  assign intr_frm_trn_tx_cmt_out = intr_frm_trn_tx_cmt;
  assign intr_buffer_over_buf_ovr_out = intr_buffer_over_buf_ovr;
  assign intr_buffer_under_buf_und_out = intr_buffer_under_buf_und;
  assign intr_mask_buf_under_out = intr_mask_buf_under;
  assign intr_mask_buf_over_out = intr_mask_buf_over;
  assign intr_mask_frm_tx_cmt_out = intr_mask_frm_tx_cmt;
  assign intr_mask_line_in_cmt_out = intr_mask_line_in_cmt;
  assign intr_mask_line_tx_cmt_out = intr_mask_line_tx_cmt;
  assign cam_ctrl_en_out = cam_ctrl_en;
  assign dma_ctrl_trig_mask_out = dma_ctrl_trig_mask;
  assign debug_ctrl_sram_buffer_out = debug_ctrl_sram_buffer;
  assign debug_ctrl_debug_en_out = debug_ctrl_debug_en;

  // Make wire assigments for SW readable registers

  assign frmt_int = ({
         {30{1'b0}},
         frmt_cam[1:0]
         });

  assign res_int = ({
         {30{1'b0}},
         res_cam[1:0]
         });

  assign intr_line_trn_int = ({
         {31{1'b0}},
         intr_line_trn_tx_cmt
         });

  assign intr_line_input_int = ({
         {31{1'b0}},
         intr_line_input_in_cmt
         });

  assign intr_frm_trn_int = ({
         {31{1'b0}},
         intr_frm_trn_tx_cmt
         });

  assign intr_buffer_over_int = ({
         {31{1'b0}},
         intr_buffer_over_buf_ovr
         });

  assign intr_buffer_under_int = ({
         {31{1'b0}},
         intr_buffer_under_buf_und
         });

  assign intr_mask_int = ({
         {27{1'b0}},
         intr_mask_buf_under,
         intr_mask_buf_over,
         intr_mask_frm_tx_cmt,
         intr_mask_line_in_cmt,
         intr_mask_line_tx_cmt
         });

  assign cam_ctrl_int = ({
         {31{1'b0}},
         cam_ctrl_en
         });

  assign dma_ctrl_int = ({
         {31{1'b0}},
         dma_ctrl_trig_mask
         });

  assign debug_ctrl_int = ({
         {30{1'b0}},
         debug_ctrl_sram_buffer,
         debug_ctrl_debug_en
         });

  // Generate read data
  always @* begin : read_mux
    reg [31:0] tmp_read_data;

    tmp_read_data = 32'b0;

    tmp_read_data = tmp_read_data | ({32{frmt_rd_en_int}} & frmt_int);
    tmp_read_data = tmp_read_data | ({32{res_rd_en_int}} & res_int);
    tmp_read_data = tmp_read_data | ({32{intr_line_trn_rd_en_int}} & intr_line_trn_int);
    tmp_read_data = tmp_read_data | ({32{intr_line_input_rd_en_int}} & intr_line_input_int);
    tmp_read_data = tmp_read_data | ({32{intr_frm_trn_rd_en_int}} & intr_frm_trn_int);
    tmp_read_data = tmp_read_data | ({32{intr_buffer_over_rd_en_int}} & intr_buffer_over_int);
    tmp_read_data = tmp_read_data | ({32{intr_buffer_under_rd_en_int}} & intr_buffer_under_int);
    tmp_read_data = tmp_read_data | ({32{intr_mask_rd_en_int}} & intr_mask_int);
    tmp_read_data = tmp_read_data | ({32{cam_ctrl_rd_en_int}} & cam_ctrl_int);
    tmp_read_data = tmp_read_data | ({32{dma_ctrl_rd_en_int}} & dma_ctrl_int);
    tmp_read_data = tmp_read_data | ({32{debug_ctrl_rd_en_int}} & debug_ctrl_int);

    read_data = tmp_read_data;
  end

  // Assign some internal to external signals

  assign address_int[6:0] = ADDRESS[6:0];
  assign RDATA[31:0] = read_data[31:0];
  assign ERR = err_int;
  assign ACK = 1'b1;

endmodule
