//-----------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//-----------------------------------------------------------------------------
// This file was auto-generated by Register Manager
//-----------------------------------------------------------------------------

module camera_ctrl_bus_interface
(
  // System bus ports
  output        PREADY,
  output [31:0] PRDATA,
  output        PSLVERR,
  input  [6:0]  PADDR,
  input  [2:0]  PPROT,
  input         PSEL,
  input         PENABLE,
  input         PWRITE,
  input  [31:0] PWDATA,
  input  [3:0]  PSTRB,
  input         PCLK,
  input         PRESETn,

  // Internal bus ports
  input  [31:0] RDATA_IN,
  input         ERR_IN,
  input         ACK_IN,
  output [6:0]  ADDRESS_OUT,
  output [31:0] WDATA_OUT,
  output        RD_OUT,
  output        VAL_OUT,
  output [3:0]  BE_OUT,
  output        SECURE_OUT,
  output        CLK_OUT,
  output        RESETn_OUT
);

`include "camera_ctrl_localparams.sv"

  wire apb_valid;
  reg  val;

  // Valid APB transfer
  assign apb_valid = ((PSEL & ~PENABLE) | (~ACK_IN & PENABLE));

  always @(posedge PCLK or negedge PRESETn)
  begin
    if (~PRESETn)
      val <= 1'b0;
    else if (apb_valid != val)
      val <= apb_valid;
  end

  assign BE_OUT = PSTRB;

  assign PRDATA = RDATA_IN;
  assign PSLVERR = ERR_IN;
  assign PREADY = ACK_IN;

  assign ADDRESS_OUT[6:0] = PSEL ? PADDR[6:0] : 7'h0;
  assign WDATA_OUT[31:0] = PSEL ? PWDATA[31:0] : 32'h0;
  assign RD_OUT = (PSEL & ~PWRITE);
  assign VAL_OUT = val;
  assign SECURE_OUT = ~PPROT[1];
  assign CLK_OUT = PCLK;
  assign RESETn_OUT = PRESETn;

endmodule
